export const SUBJECT_TYPES = {
    SET_SUBJECT: 'SET_SUBJECT',
    CLEAR_SUBJECT_STATE: 'CLEAR_SUBJECT_STATE',
    SET_TOPIC: 'SET_TOPIC',
    CLEAR_TOPIC_STATE: 'CLEAR_TOPIC_STATE',
    SET_NOTE: 'SET_NOTE',
    UPDATE_STATE: 'UPDATE_STATE',
    CLEAR_NOTE_STATE: 'CLEAR_NOTE_STATE',
    SET_SUBJECT_LIST: 'SET_SUBJECT_LIST',
    CLEAR_STATE: 'CLEAR_STATE',
};